---
title: "Index"
format: html
editor: visual
---

```{r}
#| label: load-packages
#| message: false

library(tidyverse)
library(sf)
library(usmap)

```

```{r}
#| label: read-data

presidents <- read_csv("data/1976-2020-president.csv", show_col_types = FALSE)

```

```{r}
#| label: data-wrangling

presidents_winner <- presidents |>
  filter(year == 1976, 
         party_simplified %in% c("DEMOCRAT", "REPUBLICAN"), 
         state != "DISTRICT OF COLUMBIA") |>
  group_by(state) |>
  filter(candidatevotes == max(candidatevotes)) |>
  ungroup() |>
  select(year, state, state_fips, candidate, party_simplified) 

presidents_winner |>
  count(candidate)

gradient_map_data <- presidents |>
  filter(party_simplified %in% c("DEMOCRAT", "REPUBLICAN"),
         state != "DISTRICT OF COLUMBIA", 
         year == 2000) |>
  select(party_simplified, year, state_fips, candidatevotes, totalvotes) |>
  mutate(perc_votes = candidatevotes / totalvotes) |>
  arrange(party_simplified) |>
  group_by(year, state_fips) |>
  reframe(rep_dem_diff = diff(perc_votes)) |>
  select(-year) |>
  rename(fips = state_fips, values = rep_dem_diff) 

```

```{r}
#| label: map

multiply_by_100 <- function(x) {
  return(paste0(x * 100, " points"))
}

plot_usmap("states", data = gradient_map_data) +
  scale_fill_gradient2(labels = multiply_by_100, low = "blue",
                       high = "red", mid = "white", midpoint = 0) +
  labs(fill = "Point Differential") +
  theme(legend.position = "right") +
  theme(legend.title = element_text(vjust = 1, face = "bold"))

```

```{r}
#| label: alternate-maps

red_blue_map_data <- presidents |>
  filter(year == 1976) |>
  group_by(state) |>
  filter(candidatevotes == max(candidatevotes)) |>
  ungroup() |>
  select(state_fips, party_detailed) |>
  rename(fips = state_fips, values = party_detailed)

plot_usmap("states", data = red_blue_map_data) +
  scale_fill_manual(values = c("blue", "red")) +
  labs(fill = "Presidential Party") +
  theme(
    legend.position = "right"
  )

```

```{r}
red_blue_map_data <- presidents |>
  filter(year == 1976) |>
  group_by(state) |>
  filter(candidatevotes == max(candidatevotes)) |>
  ungroup() |>
  select(state_fips, party_detailed) |>
  rename(fips = state_fips, values = party_detailed)

plot_usmap("states", include = "OH", data = red_blue_map_data, show.legend = FALSE) +
  scale_fill_manual(values = c("blue", "red")) +
  labs(fill = "Presidential Party") +
  theme(
    legend.position = "right"
  )
```

```{r}
red_blue_map_data <- presidents |>
  filter(year == 1976) |>
  group_by(state) |>
  filter(candidatevotes == max(candidatevotes)) |>
  ungroup() |>
  select(state_fips, party_detailed) |>
  rename(fips = state_fips, values = party_detailed)

plot_usmap("states", include = "AZ", data = red_blue_map_data, show.legend = FALSE) +
  scale_fill_manual(values = c("DEMOCRAT" = "blue", "REPUBLICAN" = "red")) +
  labs(fill = "Presidential Party") +
  theme(
    legend.position = "right"
  )
```

```{r}
red_blue_map_data <- presidents |>
  filter(year == 1976) |>
  group_by(state) |>
  filter(candidatevotes == max(candidatevotes)) |>
  ungroup() |>
  select(state_fips, party_detailed) |>
  rename(fips = state_fips, values = party_detailed)

plot_usmap("states", include = "NC", data = red_blue_map_data, show.legend = FALSE) +
  scale_fill_manual(values = c("DEMOCRAT" = "blue", "REPUBLICAN" = "red")) +
  labs(fill = "Presidential Party") +
  theme(
    legend.position = "right"
  )
```

```{r}
red_blue_map_data <- presidents |>
  filter(year == 1976) |>
  group_by(state) |>
  filter(candidatevotes == max(candidatevotes)) |>
  ungroup() |>
  select(state_fips, party_detailed) |>
  rename(fips = state_fips, values = party_detailed)

plot_usmap("states", include = "IA", data = red_blue_map_data, show.legend = FALSE) +
  scale_fill_manual(values = c("DEMOCRAT" = "blue", "REPUBLICAN" = "red")) +
  labs(fill = "Presidential Party") +
  theme(
    legend.position = "right"
  )
```
