---
title: "Proposal"
format: html
editor: visual
---

# Data

```{r}
#| label: data
#| message: false

library(tidyverse)

presidents <- read_csv("data/1976-2020-president.csv", show_col_types = FALSE)

```

# Overview

Overall, we want to create an animated spatio-temporal visualization to explore state voting tendencies in US presidential elections since 1976.

# Goals

We are interested in voting behaviors in states in the US and examining whether the distribution of votes for political parties has changed over time. We find this topic exciting because we are in an election year and the upcoming presidential election is a current topic of discussion among many students on campus. Another area of interest to our team is how the number of third party votes (for candidates not in the Republican and Democratic parties) has changed since 1976. While a third party candidate has never won a presidential election in the United States, the rise of public figures such as Kanye West running for president has drawn mass media attention in recent news. The members of our team are from Alabama, Arizona, Missouri, and New York, so we are especially interested to examine past voting behaviors in our home states and see how it has changed over the past 45 years. We plan to plot a US map for every presidential election year and then create an animation by putting together the maps for all the years. The color of the state (red or blue) will represent the political party of the candidate who won that state's election and the intensity of the color will measure how Republican or Democrat-leaning the state is. Alternatively, if we run into challenges with animation or want to change focus, we are also interested in creating an interactive, informational Shiny dashboard where users could click on specific states and years to see which candidate won that state's election in the given year.

Our data set has voting records for every state in the US for every presidential election from 1976 to 2020, including how many votes every candidate got and the parties of those candidates. There are `{r} nrow(presidents)` total observations, each representing a presidential candidate, and `{r} ncol(presidents)` variables. These variables are both numeric, such as the election year and how many votes a candidate received, and categorical, including the state that the candidate ran in, their political party, and whether they were a write-in candidate or not. The MIT Election Data and Science Lab (MEDSL) originally created the data set in 2017, and we accessed it through the Harvard Dataverse website. We chose this particular data set because it is from a reputable source for election data and it includes candidates who received votes besides the Democrat and Republican candidates. This will be important for our investigation into the potential rise of third-party candidates.

[Data source](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/42MVDX)

# Plan of Attack

Week 1 (March 18): Team members will work in lab to develop focus of project, pick a data set, and start working on project proposal. All team members will contribute outside of class.

Week 2 (March 25): Team will finish project proposal by lab on Wednesday. In lab, team will review other team's proposals and complete peer reviews. After lab, team members will communicate to update proposal based on peer feedback. Team will submit updated project proposal by 5pm on Friday.

Week 3 (April 1): After receiving feedback on the proposal from teaching team, team will meet outside of class to make any necessary edits, start working, and delegate tasks. The entire team will start working on creating the first US visualization for 1976 and will agree upon the map before recreating the plot for every election year after 1976. Two team members will start to research animation techniques.

Week 4 (April 8): The team will complete one map for 1976 and start working on duplicating the technique for all other election years. Animation sub-team will continue to research animation techniques.

Week 5 (April 15): The maps should be completed. The team will then focus on animation and assembling all the maps together.

Week 6 (April 22): Team will finish most or all of project by lab on Wednesday. In lab, team will review other team's code and complete peer reviews. After lab, team members will communicate to update project based on peer feedback. Team will then meet to finalize project and start preparing for presentation.

Week 7 (April 29): Outside of class, team will meet to put any finishing touches on the project and practice for the presentation. Final project and presentation is due on Wednesday, May 1st at 9am.
