---
title: "️US Presidential Elections"
format: dashboard
server: shiny
---

```{r}
#| context: setup

library(tidyverse)
library(DT)
library(shiny)
library(usmap)

presidents <- read_csv("data/1976-2020-president.csv", show_col_types = FALSE)
```

## {.sidebar}

```{r}

selectInput(
    inputId = "input_year",
    label = strong("Election Year"),
    choices = unique(presidents$year),
    selected = "2000"
  )
```

# Data

```{r}
tableOutput('data')
```

```{r}
plotOutput("red_blue_map")
```

```{r}
#| context: server

red_blue_map_data <- reactive({
  presidents |>
    filter(year == input$input_year) |>
    group_by(state) |>
    filter(candidatevotes == max(candidatevotes)) |>
    ungroup() |>
    select(state_fips, party_simplified) |>
    rename(fips = state_fips, values = party_simplified)
})


output$data <- renderTable({
  presidents
})

output$red_blue_map <- renderPlot({
  plot_usmap("states", data = red_blue_map_data()) +
  scale_fill_manual(values = c("#346EF0", "#EB3323")) +
  labs(fill = "Presidential Party") +
  theme(
    legend.position = "right",
    legend.title = element_text(vjust = 1, size = 14),
    legend.key.size = unit(1.2, "cm"),
    legend.text = element_text(size = 12)
  )
})
```



```{r}
swing_states <- presidents |>
  filter(
    party_simplified %in% c("DEMOCRAT", "REPUBLICAN"),
    state != "DISTRICT OF COLUMBIA",
    year == 2016
  ) |>
  select(party_simplified, year, state_fips, candidatevotes, totalvotes) |>
  mutate(perc_votes = candidatevotes / totalvotes) |>
  arrange(party_simplified) |>
  group_by(year, state_fips) |>
  reframe(rep_dem_diff = diff(perc_votes)) |>
  select(-year) |>
  rename(fips = state_fips, values = rep_dem_diff) |>
  filter(
    abs(values) < 0.03
  ) |>
  mutate(values = TRUE)
swing_states

plot_usmap("states", data = swing_states) +
    scale_fill_manual(values = "#BA68C8", na.value = "#D3D3D3") +
    labs(fill = "Swing State") +
    theme(
      legend.position = "none"
    )


```
```{r}

swing_states_red_blue <-
  presidents |>
    filter(
      party_simplified %in% c("DEMOCRAT", "REPUBLICAN"),
      year == 1984, 
      state_fips == 27
    ) |>
    select(state_fips, party_simplified) |>
    rename(fips = state_fips, values = party_simplified)


plot_usmap("states", data = swing_states_red_blue) +
    scale_fill_manual(values = c("#EB3323", "#346EF0"), 
                      na.value = "#D3D3D3") +
    labs(fill = "Swing State") +
    theme(
      legend.position = "none"
    )
```

